### ISSUE TITLE
More than one exclusion doesn't work

### ISSUE THREAD

**Issue by FlorentinBurgeat** [Korko/SecretSanta.fr#101]
I created a event with two exclusions for me, and I found out that my target was one of the people I excluded.

It seems not to appear with only one exclusion.

**Comment by Korko** [comment]
Thanks for the report, I'll take a look immediatly!

**Comment by Korko** [comment]
Ok so that's worse than I thought. The plugin vue-multiselect doesn't transmit any data via the form submit. See https://github.com/shentao/vue-multiselect/issues/1124. I'll fix that quickly.

**Comment by FlorentinBurgeat** [comment]
Nice! Thx !
