### ISSUE TITLE
Cannot send SMS?

### ISSUE THREAD

**Issue by blat** [Korko/SecretSanta.fr#43]
Hello,

Tout d'abord, merci beaucoup pour ce service très utile et avec pile ce qu'il faut comme settings (pas d'inscription, email ou sms, règles d'exclusion et templating des messages envoyés).

Je l'ai testé il y environ 10 jours, et tout fonctionnait, mais aujourd'hui, dès que je saisi un numéro de téléphone pour les SMS, j'obtiens une erreur 500.

Est-ce moi qui le saisi mal ou y a t il un problème de ton coté ?
J'ai essayé plusieurs formats, 0612345678, 612345678, +33612345678 mais toujours la même erreur.

Je tente de faire un tirage "familial", du coup tout le monde n'a pas d'email...

Merci d'avance pour ton aide :)

Mickael

**Comment by Korko** [comment]
Salut Mickael,
Désolé pour le temps de réponse, je ne consulte plus trop github, j'ai switché sur la version "libre" hébergée par Framasoft : https://framagit.org/Korko/
Bref, en effet il y avait un problème avec l'envoi des SMS qui a été réglé le 5 décembre au soir je crois.
Une erreur idiote de mot de passe et une mauvaise gestion des erreurs malheureusement.

Bref c'est fixé, si tu as d'autres problèmes, n'hésite surtout pas à m'écrire directement : jeremy.lemesle@korko.fr ou à poster sur https://framagit.org/Korko/SecretSanta un ticket (selon ton envie de t'inscrire sur un autre site, entre un autre xD) ! ^^
